<a href="https://colab.research.google.com/github/CSM-12/pytorch_machine_learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.randint(1,10, (7,7))
print(tensor)

tensor([[2, 7, 3, 7, 7, 3, 9],
        [9, 2, 3, 1, 1, 6, 9],
        [2, 8, 6, 8, 6, 9, 4],
        [9, 1, 4, 7, 7, 2, 3],
        [1, 8, 1, 1, 9, 2, 4],
        [4, 9, 1, 4, 7, 5, 5],
        [2, 4, 7, 5, 4, 7, 4]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.randint(1,10, (7,7))
# Perform matrix multiplication
tensorMultiplication = torch.matmul(tensor, tensor2)
print(tensorMultiplication)

tensor([[176, 223, 183, 190, 184, 172, 149],
        [136, 202, 145, 106, 107, 111, 118],
        [159, 273, 186, 193, 211, 203, 161],
        [152, 209, 139, 116, 164, 167, 159],
        [ 76, 159, 113, 112, 123, 117,  85],
        [123, 218, 143, 154, 169, 153, 133],
        [125, 212, 154, 137, 147, 154, 116]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
randTensor1 = torch.randint(1, 10, (7,1))
randTensor2 = torch.randint(1, 10, (1,7))

print(randTensor1)

# Matrix multiply tensors
print(torch.matmul(randTensor1, randTensor2))

tensor([[9],
        [1],
        [3],
        [7],
        [8],
        [7],
        [8]])
tensor([[18, 18,  9, 81, 27, 63, 36],
        [ 2,  2,  1,  9,  3,  7,  4],
        [ 6,  6,  3, 27,  9, 21, 12],
        [14, 14,  7, 63, 21, 49, 28],
        [16, 16,  8, 72, 24, 56, 32],
        [14, 14,  7, 63, 21, 49, 28],
        [16, 16,  8, 72, 24, 56, 32]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
print(torch.cuda.is_available())
torch.cuda.manual_seed(1234)

True



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")

# Create two random tensors on GPU
randomTensor1 = torch.rand(2,3, device=device)

torch.cuda.manual_seed(1234)
randomTensor2 = torch.rand(2,3, device=device)

print(randomTensor1)
print(randomTensor2)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
mul = torch.matmul(randomTensor1, randomTensor2.T)
print(mul)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
print(torch.max(mul))
# Find min
print(torch.min(mul))

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
